---
- name: Set up infrastructure-related parameters
  template:
    src: '{{ playbook_dir }}/templates/parameters.yml.dist'
    dest: '{{ ansistrano_release_path.stdout }}/app/config/parameters.yml'

- name: Install Composer dependencies
  composer:
    command: install
    working_dir: '{{ ansistrano_release_path.stdout }}'

- name: Clear the cache
  command: '{{ release_console_path }} cache:clear --no-warmup --env=prod'

- name: Warm up the cache
  command: '{{ release_console_path }} cache:warmup --env=prod'

- name: Install bundle assets
  command: '{{ release_console_path }} assets:install {{ release_web_path }} --symlink --no-debug --env=prod'

- name: Setup owner and group of files in var/ dir
  become: true
  file:
    path: '{{ release_var_path }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: www-data
    recurse: yes

- name: Setup directories permissions in var/ dir
  become: true
  command: 'find {{ release_var_path }} -type d -exec chmod 0555 {} \;'

- name: Setup files permissions in var/ dir
  become: true
  command: 'find {{ release_var_path }} -type f -exec chmod 0444 {} \;'

- name: Setup directories permissions in logs/ dir
  become: true
  command: 'find {{ release_logs_path }} -type d -exec chmod 0775 {} \;'

- name: Setup directories permissions in sessions/ dir
  become: true
  command: 'find {{ release_sessions_path }} -type d -exec chmod 0775 {} \;'
