---
- name: Set up infrastructure-related parameters
  template:
    src: '{{ playbook_dir }}/templates/parameters.yml.dist'
    dest: '{{ ansistrano_release_path.stdout }}/app/config/parameters.yml'

- name: Install Composer dependencies
  composer:
    command: install
    working_dir: '{{ ansistrano_release_path.stdout }}'

- name: Clear the cache
  command: '{{ release_console_path }} cache:clear --no-warmup --env=prod'

- name: Warm up the cache
  command: '{{ release_console_path }} cache:warmup --env=prod'

- name: Create DB if not exists
  command: '{{ release_console_path }} doctrine:database:create --if-not-exists --env=prod'
  register: db_create_output
  changed_when: not db_create_output.stdout|search('already exists. Skipped')

- name: Create schema if DB was just created
  command: '{{ release_console_path }} doctrine:schema:create --env=prod'
  register: schema_create_output
  when: db_create_output|changed

- name: Skip all migrations if DB schema was just created
  command: '{{ release_console_path }} doctrine:migrations:version --add --all --no-interaction --env=prod'
  register: skip_migrations_output
  when: schema_create_output|changed

- name: Run migrations
  command: '{{ release_console_path }} doctrine:migrations:migrate --no-interaction --env=prod'
  register: run_migrations_output
  changed_when: not run_migrations_output.stdout|search('No migrations to execute')
  when: not skip_migrations_output|changed

- name: Install bundle assets
  command: '{{ release_console_path }} assets:install {{ release_web_path }} --symlink --no-debug --env=prod'

- name: Install Node dependencies
  command: yarn install
  args:
    chdir: '{{ ansistrano_release_path.stdout }}'
  register: yarn_install_output
  changed_when: not yarn_install_output.stdout|search("Already up-to-date")

- name: Install Webpack Encore assets
  command: './node_modules/.bin/encore production'
  args:
    chdir: '{{ ansistrano_release_path.stdout }}'

- name: Setup owner and group of files in var/ dir
  become: true
  file:
    path: '{{ release_var_path }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: www-data
    recurse: yes

- name: Setup directories permissions in var/ dir
  become: true
  command: 'find {{ release_var_path }} -type d -exec chmod 0555 {} \;'

- name: Setup files permissions in var/ dir
  become: true
  command: 'find {{ release_var_path }} -type f -exec chmod 0444 {} \;'

- name: Setup directories permissions in logs/ dir
  become: true
  command: 'find {{ release_logs_path }} -type d -exec chmod 0775 {} \;'

- name: Setup directories permissions in sessions/ dir
  become: true
  command: 'find {{ release_sessions_path }} -type d -exec chmod 0775 {} \;'
